repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args: [ --unsafe ]
      - id: check-xml
      - id: check-case-conflict
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: ed07c6e8889cf83a7245866d1dd007d1f93bf55e  # frozen: 0.9.13
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 36243b70e5ce219623c3503f5afba0f8c96fda55  # frozen: v0.14.7
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
  # mdformat plugins are not all compatible with mdformat 1.0.0 yet.
  - repo: https://github.com/hukkin/mdformat
    rev: 83dc2ce5ca115d3390b9b5561d2898366faf0742  # frozen: 0.7.2
    hooks:
      - id: mdformat
        additional_dependencies:
          - git+https://github.com/Freed-Wu/mdformat-ruff@6cd00a4d513758d487fa782ab4cac8f1a61e842d   # 0.1.3
          - git+https://github.com/KyleKing/mdformat-gfm-alerts@989aa51cf459559af5d3dae948cbeeab712bd186  # 2.0.0
          - git+https://github.com/KyleKing/mdformat-mkdocs@095c99065f8bc1f879f090da0c48baf5e2cc5f38  # 5.1.1
          - git+https://github.com/butler54/mdformat-frontmatter@93bb972b6044d22043d6c191a2e73858ff09d3e5  # 2.0.8
          - git+https://github.com/executablebooks/mdformat-footnote@8f96af4e089ede7e45979444deedef0fd5fb2aeb  # 0.1.2
          - git+https://github.com/hukkin/mdformat-gfm@1c2d3c68019d93ff30c69482b0b19098b41b0a17  # 1.0.0
          - git+https://github.com/hukkin/mdformat-toc@ac1c5c919bf7e8c044153447c8cb853de599b70e  # 0.5.0
