name: Deploy Docs
on:
  workflow_dispatch:
  push:
    branches:
      - docs

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - uses: astral-sh/setup-uv@v4
        with:
          version: "0.7.18"
          enable-cache: true
      - name: Build and push docs version
        run: uv run mkdocs gh-deploy --force
      - name: Add CNAME
        run: |
          git switch gh-pages
          echo "docs.evidential.dev" > CNAME
          if [ ! -f CNAME ]; then
            echo "docs.evidential.dev" > CNAME
            git add CNAME
            git commit -m "Add CNAME for custom domain"
            git push origin gh-pages
          fi
