name: Deploy Docs
on:
  workflow_dispatch:
  push:
    branches:
      - docs
  pull_request:
    branches:
      - docs

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-26.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1  # zizmor: ignore[artipacked] for gh_deploy
      - uses: j178/prek-action@4e14d07f9231acabce116ccfca13b13dd9755ece # v3.0.0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
      - name: Build docs
        if: github.event_name == 'pull_request'
        run: uv run mkdocs build
      - name: Build and push docs
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: uv run mkdocs gh-deploy --force
      - name: Add CNAME
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          git switch gh-pages
          echo "docs.evidential.dev" > CNAME
          if [ ! -f CNAME ]; then
            echo "docs.evidential.dev" > CNAME
            git add CNAME
            git commit -m "Add CNAME for custom domain"
            git push origin gh-pages
          fi
